import type { Job, Candidate, AIEvaluation, EvaluationRubric, AuditEntry } from './types';

export const MOCK_JOBS: Job[] = [
  {
    id: 'job-1',
    title: 'Senior Frontend Engineer',
    department: 'Engineering',
    location: 'San Francisco, CA',
    type: 'full-time',
    status: 'active',
    description: `We are looking for a Senior Frontend Engineer to join our growing team. You will be responsible for building and maintaining our web applications, working closely with designers and backend engineers to deliver exceptional user experiences.

The ideal candidate has deep expertise in React and TypeScript, a keen eye for UI/UX details, and experience with modern frontend tooling and practices.`,
    requirements: [
      '5+ years of frontend development experience',
      'Expert-level React and TypeScript skills',
      'Experience with state management (Redux, Zustand, etc.)',
      'Strong understanding of web performance optimization',
      'Experience with testing frameworks (Jest, Cypress)',
      'Excellent communication and collaboration skills',
    ],
    createdAt: '2025-01-15T10:00:00Z',
    updatedAt: '2025-01-20T14:30:00Z',
    candidatesCount: 24,
  },
  {
    id: 'job-2',
    title: 'Product Designer',
    department: 'Design',
    location: 'Remote',
    type: 'remote',
    status: 'active',
    description: `Join our design team to create beautiful, intuitive interfaces for our AI-powered recruitment platform. You'll work on the entire design process from research and ideation to prototyping and handoff.

We're looking for someone who can balance aesthetics with usability and has experience designing for complex workflows.`,
    requirements: [
      '4+ years of product design experience',
      'Strong portfolio demonstrating UI/UX work',
      'Proficiency in Figma and prototyping tools',
      'Experience with design systems',
      'Understanding of accessibility standards',
      'Ability to conduct and synthesize user research',
    ],
    createdAt: '2025-01-10T09:00:00Z',
    updatedAt: '2025-01-18T11:00:00Z',
    candidatesCount: 18,
  },
  {
    id: 'job-3',
    title: 'Machine Learning Engineer',
    department: 'AI/ML',
    location: 'New York, NY',
    type: 'full-time',
    status: 'active',
    description: `We're building the future of AI-powered recruitment and need an ML Engineer to help develop our candidate matching and evaluation algorithms.

You'll work on NLP models for resume parsing, recommendation systems for candidate matching, and bias detection in hiring processes.`,
    requirements: [
      '3+ years of ML engineering experience',
      'Strong Python and ML framework skills (PyTorch/TensorFlow)',
      'Experience with NLP and transformer models',
      'Knowledge of MLOps practices',
      'Experience deploying models to production',
      'MS/PhD in Computer Science or related field preferred',
    ],
    createdAt: '2025-01-05T08:00:00Z',
    updatedAt: '2025-01-22T16:00:00Z',
    candidatesCount: 12,
  },
  {
    id: 'job-4',
    title: 'Customer Success Manager',
    department: 'Customer Success',
    location: 'Austin, TX',
    type: 'full-time',
    status: 'paused',
    description: `Help our enterprise customers succeed with Visiontact. You'll be the primary point of contact for key accounts, ensuring they get maximum value from our platform.`,
    requirements: [
      '3+ years in customer success or account management',
      'Experience with B2B SaaS products',
      'Strong presentation and communication skills',
      'Data-driven approach to customer health',
      'Experience with CRM tools',
    ],
    createdAt: '2024-12-20T10:00:00Z',
    updatedAt: '2025-01-10T09:00:00Z',
    candidatesCount: 8,
  },
  {
    id: 'job-5',
    title: 'DevOps Engineer',
    department: 'Engineering',
    location: 'Remote',
    type: 'remote',
    status: 'draft',
    description: `Build and maintain our cloud infrastructure. You'll work on CI/CD pipelines, monitoring, and security practices to keep our platform running smoothly.`,
    requirements: [
      '4+ years of DevOps/SRE experience',
      'Strong AWS or GCP experience',
      'Kubernetes and containerization expertise',
      'Infrastructure as code (Terraform/Pulumi)',
      'Monitoring and observability tools',
    ],
    createdAt: '2025-01-25T10:00:00Z',
    updatedAt: '2025-01-25T10:00:00Z',
    candidatesCount: 0,
  },
];

export const MOCK_CANDIDATES: Candidate[] = [
  // Senior Frontend Engineer candidates
  {
    id: 'cand-1',
    jobId: 'job-1',
    name: 'Sarah Chen',
    email: 'sarah.chen@email.com',
    phone: '+1 (555) 123-4567',
    role: 'Senior Frontend Engineer',
    experience: 7,
    skills: ['React', 'TypeScript', 'GraphQL', 'Node.js', 'AWS', 'Testing'],
    stage: 'interview',
    score: 92,
    appliedAt: '2025-01-16T08:00:00Z',
    updatedAt: '2025-01-22T10:00:00Z',
    linkedinUrl: 'https://linkedin.com/in/sarahchen',
  },
  {
    id: 'cand-2',
    jobId: 'job-1',
    name: 'Marcus Johnson',
    email: 'marcus.j@email.com',
    phone: '+1 (555) 234-5678',
    role: 'Lead Frontend Developer',
    experience: 6,
    skills: ['React', 'Vue.js', 'TypeScript', 'CSS', 'Webpack'],
    stage: 'shortlisted',
    score: 85,
    appliedAt: '2025-01-17T14:00:00Z',
    updatedAt: '2025-01-20T09:00:00Z',
  },
  {
    id: 'cand-3',
    jobId: 'job-1',
    name: 'Emma Williams',
    email: 'emma.w@email.com',
    phone: '+1 (555) 345-6789',
    role: 'Frontend Engineer',
    experience: 4,
    skills: ['React', 'JavaScript', 'CSS', 'HTML', 'Jest'],
    stage: 'applied',
    score: 72,
    appliedAt: '2025-01-18T11:00:00Z',
    updatedAt: '2025-01-18T11:00:00Z',
  },
  {
    id: 'cand-4',
    jobId: 'job-1',
    name: 'David Kim',
    email: 'david.kim@email.com',
    phone: '+1 (555) 456-7890',
    role: 'Full Stack Developer',
    experience: 5,
    skills: ['React', 'Node.js', 'PostgreSQL', 'Docker', 'TypeScript'],
    stage: 'shortlisted',
    score: 88,
    appliedAt: '2025-01-16T16:00:00Z',
    updatedAt: '2025-01-21T14:00:00Z',
    linkedinUrl: 'https://linkedin.com/in/davidkim',
  },
  {
    id: 'cand-5',
    jobId: 'job-1',
    name: 'Lisa Thompson',
    email: 'lisa.t@email.com',
    phone: '+1 (555) 567-8901',
    role: 'Senior UI Developer',
    experience: 8,
    skills: ['React', 'Angular', 'SCSS', 'Accessibility', 'Design Systems'],
    stage: 'interview',
    score: 90,
    appliedAt: '2025-01-15T10:00:00Z',
    updatedAt: '2025-01-23T11:00:00Z',
  },
  {
    id: 'cand-6',
    jobId: 'job-1',
    name: 'James Rodriguez',
    email: 'james.r@email.com',
    phone: '+1 (555) 678-9012',
    role: 'Frontend Developer',
    experience: 3,
    skills: ['React', 'JavaScript', 'CSS'],
    stage: 'rejected',
    score: 45,
    appliedAt: '2025-01-17T09:00:00Z',
    updatedAt: '2025-01-19T15:00:00Z',
    notes: 'Insufficient experience with TypeScript and testing frameworks.',
  },
  {
    id: 'cand-7',
    jobId: 'job-1',
    name: 'Aisha Patel',
    email: 'aisha.p@email.com',
    phone: '+1 (555) 789-0123',
    role: 'Senior Frontend Engineer',
    experience: 6,
    skills: ['React', 'TypeScript', 'Redux', 'Cypress', 'Performance'],
    stage: 'applied',
    score: 82,
    appliedAt: '2025-01-20T13:00:00Z',
    updatedAt: '2025-01-20T13:00:00Z',
  },
  {
    id: 'cand-8',
    jobId: 'job-1',
    name: 'Michael Brown',
    email: 'michael.b@email.com',
    phone: '+1 (555) 890-1234',
    role: 'Tech Lead - Frontend',
    experience: 9,
    skills: ['React', 'TypeScript', 'Architecture', 'Team Leadership', 'Mentoring'],
    stage: 'applied',
    score: 78,
    appliedAt: '2025-01-21T08:00:00Z',
    updatedAt: '2025-01-21T08:00:00Z',
  },
  // Product Designer candidates
  {
    id: 'cand-9',
    jobId: 'job-2',
    name: 'Olivia Martinez',
    email: 'olivia.m@email.com',
    phone: '+1 (555) 901-2345',
    role: 'Senior Product Designer',
    experience: 5,
    skills: ['Figma', 'User Research', 'Prototyping', 'Design Systems', 'Accessibility'],
    stage: 'interview',
    score: 94,
    appliedAt: '2025-01-11T09:00:00Z',
    updatedAt: '2025-01-20T16:00:00Z',
  },
  {
    id: 'cand-10',
    jobId: 'job-2',
    name: 'Nathan Lee',
    email: 'nathan.l@email.com',
    phone: '+1 (555) 012-3456',
    role: 'UX Designer',
    experience: 4,
    skills: ['Figma', 'Sketch', 'User Testing', 'Wireframing'],
    stage: 'shortlisted',
    score: 81,
    appliedAt: '2025-01-12T14:00:00Z',
    updatedAt: '2025-01-18T10:00:00Z',
  },
  // ML Engineer candidates
  {
    id: 'cand-11',
    jobId: 'job-3',
    name: 'Dr. Rachel Green',
    email: 'rachel.g@email.com',
    phone: '+1 (555) 111-2222',
    role: 'ML Research Scientist',
    experience: 4,
    skills: ['PyTorch', 'NLP', 'Transformers', 'Python', 'MLOps'],
    stage: 'interview',
    score: 96,
    appliedAt: '2025-01-06T10:00:00Z',
    updatedAt: '2025-01-22T14:00:00Z',
  },
  {
    id: 'cand-12',
    jobId: 'job-3',
    name: 'Alex Turner',
    email: 'alex.t@email.com',
    phone: '+1 (555) 222-3333',
    role: 'ML Engineer',
    experience: 3,
    skills: ['TensorFlow', 'Python', 'Computer Vision', 'AWS SageMaker'],
    stage: 'applied',
    score: 75,
    appliedAt: '2025-01-10T11:00:00Z',
    updatedAt: '2025-01-10T11:00:00Z',
  },
];

export const MOCK_EVALUATIONS: Record<string, AIEvaluation> = {
  'cand-1': {
    candidateId: 'cand-1',
    overallScore: 92,
    strengths: [
      'Extensive React and TypeScript experience (7 years)',
      'Strong track record with production applications at scale',
      'Experience with GraphQL aligns with our stack',
      'Demonstrated testing practices and code quality focus',
    ],
    concerns: [
      'Limited experience with our specific state management solution',
      'May be overqualified for some tasks',
    ],
    recommendation: 'strongly_recommend',
    criteriaScores: [
      { criterionId: 'crit-1', criterionName: 'Technical Skills', score: 95, maxScore: 100 },
      { criterionId: 'crit-2', criterionName: 'Experience Level', score: 90, maxScore: 100 },
      { criterionId: 'crit-3', criterionName: 'Communication', score: 88, maxScore: 100 },
      { criterionId: 'crit-4', criterionName: 'Culture Fit', score: 92, maxScore: 100 },
    ],
    generatedAt: '2025-01-22T10:00:00Z',
  },
  'cand-5': {
    candidateId: 'cand-5',
    overallScore: 90,
    strengths: [
      'Deep expertise in accessibility and design systems',
      '8 years of frontend experience',
      'Strong understanding of UI/UX principles',
      'Experience mentoring junior developers',
    ],
    concerns: [
      'Angular experience may not transfer directly',
      'Salary expectations may be above budget',
    ],
    recommendation: 'recommend',
    criteriaScores: [
      { criterionId: 'crit-1', criterionName: 'Technical Skills', score: 88, maxScore: 100 },
      { criterionId: 'crit-2', criterionName: 'Experience Level', score: 95, maxScore: 100 },
      { criterionId: 'crit-3', criterionName: 'Communication', score: 92, maxScore: 100 },
      { criterionId: 'crit-4', criterionName: 'Culture Fit', score: 85, maxScore: 100 },
    ],
    generatedAt: '2025-01-23T11:00:00Z',
  },
  'cand-9': {
    candidateId: 'cand-9',
    overallScore: 94,
    strengths: [
      'Exceptional portfolio with relevant B2B SaaS work',
      'Strong user research methodology',
      'Experience building design systems from scratch',
      'Excellent communication and presentation skills',
    ],
    concerns: [
      'No direct experience in HR tech/recruitment industry',
    ],
    recommendation: 'strongly_recommend',
    criteriaScores: [
      { criterionId: 'crit-1', criterionName: 'Design Skills', score: 96, maxScore: 100 },
      { criterionId: 'crit-2', criterionName: 'Portfolio Quality', score: 94, maxScore: 100 },
      { criterionId: 'crit-3', criterionName: 'Research Skills', score: 92, maxScore: 100 },
      { criterionId: 'crit-4', criterionName: 'Culture Fit', score: 94, maxScore: 100 },
    ],
    generatedAt: '2025-01-20T16:00:00Z',
  },
  'cand-11': {
    candidateId: 'cand-11',
    overallScore: 96,
    strengths: [
      'PhD with focus on NLP and transformers',
      'Published papers in relevant domains',
      'Production ML experience at scale',
      'Strong Python and MLOps skills',
    ],
    concerns: [
      'May prefer research-heavy role',
    ],
    recommendation: 'strongly_recommend',
    criteriaScores: [
      { criterionId: 'crit-1', criterionName: 'ML Expertise', score: 98, maxScore: 100 },
      { criterionId: 'crit-2', criterionName: 'NLP Knowledge', score: 96, maxScore: 100 },
      { criterionId: 'crit-3', criterionName: 'Production Experience', score: 92, maxScore: 100 },
      { criterionId: 'crit-4', criterionName: 'Culture Fit', score: 94, maxScore: 100 },
    ],
    generatedAt: '2025-01-22T14:00:00Z',
  },
};

export const MOCK_RUBRICS: Record<string, EvaluationRubric> = {
  'job-1': {
    jobId: 'job-1',
    criteria: [
      {
        id: 'crit-1',
        jobId: 'job-1',
        name: 'Technical Skills',
        description: 'Proficiency in React, TypeScript, and modern frontend technologies',
        weight: 35,
        order: 1,
      },
      {
        id: 'crit-2',
        jobId: 'job-1',
        name: 'Experience Level',
        description: 'Years of relevant experience and complexity of past projects',
        weight: 25,
        order: 2,
      },
      {
        id: 'crit-3',
        jobId: 'job-1',
        name: 'Communication',
        description: 'Ability to articulate technical concepts and collaborate effectively',
        weight: 20,
        order: 3,
      },
      {
        id: 'crit-4',
        jobId: 'job-1',
        name: 'Culture Fit',
        description: 'Alignment with company values and team dynamics',
        weight: 20,
        order: 4,
      },
    ],
    totalWeight: 100,
    isValid: true,
  },
  'job-2': {
    jobId: 'job-2',
    criteria: [
      {
        id: 'crit-5',
        jobId: 'job-2',
        name: 'Design Skills',
        description: 'Visual design ability, attention to detail, and craft',
        weight: 30,
        order: 1,
      },
      {
        id: 'crit-6',
        jobId: 'job-2',
        name: 'Portfolio Quality',
        description: 'Quality and relevance of past design work',
        weight: 30,
        order: 2,
      },
      {
        id: 'crit-7',
        jobId: 'job-2',
        name: 'Research Skills',
        description: 'User research methodology and synthesis abilities',
        weight: 20,
        order: 3,
      },
      {
        id: 'crit-8',
        jobId: 'job-2',
        name: 'Culture Fit',
        description: 'Alignment with company values and team dynamics',
        weight: 20,
        order: 4,
      },
    ],
    totalWeight: 100,
    isValid: true,
  },
  'job-3': {
    jobId: 'job-3',
    criteria: [
      {
        id: 'crit-9',
        jobId: 'job-3',
        name: 'ML Expertise',
        description: 'Deep knowledge of machine learning algorithms and frameworks',
        weight: 35,
        order: 1,
      },
      {
        id: 'crit-10',
        jobId: 'job-3',
        name: 'NLP Knowledge',
        description: 'Specific experience with NLP and transformer models',
        weight: 25,
        order: 2,
      },
      {
        id: 'crit-11',
        jobId: 'job-3',
        name: 'Production Experience',
        description: 'Experience deploying and maintaining ML systems in production',
        weight: 25,
        order: 3,
      },
      {
        id: 'crit-12',
        jobId: 'job-3',
        name: 'Culture Fit',
        description: 'Alignment with company values and team dynamics',
        weight: 15,
        order: 4,
      },
    ],
    totalWeight: 100,
    isValid: true,
  },
};

export const MOCK_AUDIT_LOGS: AuditEntry[] = [
  {
    id: 'audit-1',
    jobId: 'job-1',
    candidateId: 'cand-1',
    action: 'candidate_moved',
    description: 'Sarah Chen moved from Shortlisted to Interview',
    performedBy: 'Alex Morgan',
    timestamp: '2025-01-22T10:00:00Z',
    metadata: { fromStage: 'shortlisted', toStage: 'interview' },
  },
  {
    id: 'audit-2',
    jobId: 'job-1',
    candidateId: 'cand-1',
    action: 'evaluation_generated',
    description: 'AI evaluation generated for Sarah Chen',
    performedBy: 'System',
    timestamp: '2025-01-22T09:55:00Z',
  },
  {
    id: 'audit-3',
    jobId: 'job-1',
    candidateId: 'cand-6',
    action: 'candidate_rejected',
    description: 'James Rodriguez rejected - insufficient experience',
    performedBy: 'Alex Morgan',
    timestamp: '2025-01-19T15:00:00Z',
  },
  {
    id: 'audit-4',
    jobId: 'job-1',
    candidateId: 'cand-2',
    action: 'candidate_shortlisted',
    description: 'Marcus Johnson moved to Shortlisted',
    performedBy: 'Alex Morgan',
    timestamp: '2025-01-20T09:00:00Z',
  },
  {
    id: 'audit-5',
    jobId: 'job-1',
    action: 'rubric_updated',
    description: 'Evaluation rubric updated - adjusted Technical Skills weight',
    performedBy: 'Jordan Lee',
    timestamp: '2025-01-18T14:30:00Z',
  },
  {
    id: 'audit-6',
    jobId: 'job-1',
    candidateId: 'cand-5',
    action: 'candidate_moved',
    description: 'Lisa Thompson moved from Shortlisted to Interview',
    performedBy: 'Alex Morgan',
    timestamp: '2025-01-23T11:00:00Z',
  },
  {
    id: 'audit-7',
    jobId: 'job-2',
    candidateId: 'cand-9',
    action: 'candidate_interviewed',
    description: 'Olivia Martinez scheduled for final interview',
    performedBy: 'Sam Taylor',
    timestamp: '2025-01-20T16:00:00Z',
  },
  {
    id: 'audit-8',
    jobId: 'job-3',
    candidateId: 'cand-11',
    action: 'evaluation_generated',
    description: 'AI evaluation generated for Dr. Rachel Green',
    performedBy: 'System',
    timestamp: '2025-01-22T14:00:00Z',
  },
  {
    id: 'audit-9',
    jobId: 'job-1',
    action: 'job_updated',
    description: 'Job requirements updated',
    performedBy: 'Jordan Lee',
    timestamp: '2025-01-20T14:30:00Z',
  },
  {
    id: 'audit-10',
    jobId: 'job-1',
    candidateId: 'cand-4',
    action: 'note_added',
    description: 'Note added for David Kim regarding technical interview',
    performedBy: 'Alex Morgan',
    timestamp: '2025-01-21T14:00:00Z',
  },
];
